title: Kevin Junger
baseline: "Couteau suisse multimédia, passionné d'automobile et amateur d'animes, de J-RPG et autres japonaiseries."
email: kevin.junger@me.com
owner: Kevin Junger
email:  kevin.junger@me.com
telephone: 0601729969
behance: kjunger
copyright: Kevin Junger
markdown: kramdown
